apps/hits/urls.py
"""Auth models."""

# Django
from django.urls import path

# Local
from apps.hits.views import (
    HitListView,
    HitDetailView,
    HitCreateView,
    HitUpdateView,
    HitBulkUpdate,
)

app_name = "hits"

urlpatterns = (
    path(
        route="hits/",
        view=HitListView.as_view(),
        name="list",
    ),
    path(
        route="hits/bulk/",
        view=HitBulkUpdate.as_view(),
        name="bulk",
    ),
    path(
        route="hits/create/",
        view=HitCreateView.as_view(),
        name="create",
    ),
    path(
        route="hits/<int:pk>/",
        view=HitDetailView.as_view(),
        name="detail",
    ),
    path(
        route="hits/<int:pk>/edit/",
        view=HitUpdateView.as_view(),
        name="update",
    ),
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

# View
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("", include("apps.hits.urls")),
    path("", include("apps.transitions.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/hits/models.py
"""Models hits app"""

# Django
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

# Third party integration
from django_fsm import FSMIntegerField, transition
from django.core.exceptions import ValidationError

# Local
from apps.hits.conditions import check_permissions


class Hit(models.Model):
    """
    Model for assigning murders
    """

    class STATE(models.IntegerChoices):
        FAILED = 0
        ASSIGNED = 1
        COMPLETED = 2

    target_name = models.CharField(max_length=256)
    mission_description = models.TextField()
    assigned = models.ForeignKey(
        to="authentication.User", on_delete=models.PROTECT, related_name="hits_assigned"
    )
    creator = models.ForeignKey(
        "authentication.User",
        null=True,
        on_delete=models.PROTECT,
        related_name="hits_creator",
    )
    state = FSMIntegerField(
        choices=STATE.choices, default=STATE.ASSIGNED, protected=True
    )

    def __str__(self):
        return f"Hit #{self.pk}"

    def get_detail_url(self):
        return reverse(
            "hits:detail",
            args=[
                self.pk,
            ],
        )

    def get_absolute_url(self):
        return self.get_detail_url()

    def get_list_url(self):
        return reverse("hits:list")

    """
        def clean(self):
        if hasattr(self, "assigned"):
            if not self.pk:
                if self.assigned.STATE == 0:
                    raise ValidationError(
                        "The selected hitman is inactive, please select a valid Hitman"
                    )
            else:
                hit = Hit.objects.get(pk=self.pk)
                if hit.assigned.pk != self.assigned.pk and self.assigned.STATE == 0:
                    raise ValidationError(
                        "The selected hitman is inactive, please select a valid Hitman"
                    )

    """

    @transition(
        field="state",
        source=STATE.ASSIGNED,
        target=STATE.FAILED,
        conditions=[
            check_permissions,
        ],
        custom=dict(
            verbose="Mark as Failed",
            btn="danger",
        ),
    )
    def failed(self, **kwargs):
        pass

    @transition(
        field="state",
        source=STATE.ASSIGNED,
        target=STATE.COMPLETED,
        conditions=[
            check_permissions,
        ],
        custom=dict(
            verbose="Mark as Completed",
            btn="success",
        ),
    )
    def completed(self, **kwargs):
        pass


@receiver(post_save, sender=Hit)
def add_creator(sender, instance, created, **kwargs):
    if created:
        from tracing.middleware import TracingMiddleware

        information = TracingMiddleware.get_info()
        user = information.get("user", False)
        instance.creator = user
        instance.save()

apps/hits/forms.py
"""Hit app forms"""
# Django
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.db.models import Q

# Third party integration
from tracing.middleware import TracingMiddleware

# Local
from apps.hits.models import Hit

User = get_user_model()


class BaseHitForm(forms.ModelForm):
    def get_base_queryset(self):
        information = TracingMiddleware.get_info()
        user = information.get("user", False)
        if user.pk == 1:
            queryset = User.objects.filter(state=1)
        else:
            queryset = user.subordinates.filter(state=1)
        if self.instance and self.instance.id:
            queryset = User.objects.filter(Q(state=1) | Q(pk=self.instance.assigned.pk))
        return queryset


class CreateHitForm(BaseHitForm):
    class Meta:
        model = Hit
        fields = ("target_name", "mission_description", "assigned")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = self.get_base_queryset()
        if self.instance and self.instance.id:
            queryset = User.objects.filter(Q(state=1) | Q(pk=self.instance.assigned.pk))
        self.fields["assigned"].queryset = queryset

    def clean_assigned(self):
        """Method to validate assigned field"""
        assigned = self.cleaned_data.get("assigned", False)
        if not assigned:
            raise ValidationError("This field is required.")
        return assigned


class UpdateHitFormActiveHitman(BaseHitForm):
    DISABLED = True

    class Meta:
        model = Hit
        fields = ("target_name", "mission_description", "assigned")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = self.get_base_queryset()
        self.fields["assigned"].queryset = queryset
        self.fields["target_name"].disabled = self.DISABLED
        self.fields["mission_description"].disabled = self.DISABLED
        self.fields["assigned"].disabled = not self.DISABLED


class UpdateHitFormInactiveHitman(UpdateHitFormActiveHitman):
    DISABLED = False

    class Meta:
        model = Hit
        fields = ("target_name", "mission_description", "assigned")


class BulkUpdateHitForm(forms.Form):
    hits = forms.ModelMultipleChoiceField(
        queryset=Hit.objects.filter(state=1), widget=forms.CheckboxSelectMultiple()
    )
    hitman = forms.ModelChoiceField(
        queryset=User.objects.filter(state=1), label="New hitman"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset_hitmen, queryset_hits = self.get_base_queryset()
        self.fields["hits"].queryset = queryset_hits
        self.fields["hitman"].queryset = queryset_hitmen

    def get_base_queryset(self):
        information = TracingMiddleware.get_info()
        user = information.get("user", False)
        if user.pk == 1:
            queryset_hitmen = User.objects.filter(state=1)
        else:
            queryset_hitmen = user.subordinates.filter(state=1) | User.objects.filter(
                pk=user.pk
            )
        queryset_hits = Hit.objects.filter(state=1, assigned__in=queryset_hitmen)

        return queryset_hitmen, queryset_hits

apps/hits/views.py
# Django
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q
from django.contrib import messages
from django.shortcuts import reverse, redirect
from django.core.exceptions import ValidationError

# Local
from apps.hits.models import Hit
from apps.authentication.models import User
from apps.hits.forms import (
    CreateHitForm,
    UpdateHitFormActiveHitman,
    UpdateHitFormInactiveHitman,
    BulkUpdateHitForm,
)


class BaseFormHit:
    model = Hit
    success_message = "created"

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, "An error has occurred")
        return super().form_invalid(form)

    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f"The hit was {self.success_message} correctly ",
        )
        return super().form_valid(form)


class HitListView(LoginRequiredMixin, ListView):
    model = Hit

    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset()

        if not user.pk == 1:
            subordinates = user.subordinates.all()
            if len(subordinates):
                return queryset.filter(Q(assigned=user) | Q(assigned__in=subordinates))
            return queryset.filter(assigned=user)
        return queryset


class HitBulkUpdate(LoginRequiredMixin, FormView):
    model = Hit
    template_name = "hits/hit_bulk.html"
    form_class = BulkUpdateHitForm

    def post(self, request, *args, **kwargs):
        hits_id = request.POST.getlist("hits", ())
        hitman_id = request.POST.get("hitman", False)
        if not hits_id:
            form = self.get_form()
            messages.add_message(
                self.request, messages.ERROR, "Please select hits to continue"
            )
            return self.form_invalid(form)
        if not hitman_id:
            form = self.get_form()
            messages.add_message(
                self.request, messages.ERROR, "Please select a hitman to continue"
            )
            return self.form_invalid(form)
        hits = Hit.objects.filter(pk__in=hits_id)
        hitman = User.objects.get(pk=hitman_id)
        hits.update(assigned=hitman)
        messages.add_message(
            self.request,
            messages.SUCCESS,
            f"The hits was reassignment correctly ",
        )
        return redirect(reverse("hits:bulk"))


class HitDetailView(LoginRequiredMixin, DetailView):
    model = Hit


class HitCreateView(LoginRequiredMixin, BaseFormHit, CreateView):
    form_class = CreateHitForm


class HitUpdateView(PermissionRequiredMixin, BaseFormHit, UpdateView):
    success_message = "updated"
    template_name = "hits/hit_update.html"

    def has_permission(self):
        self.object = self.get_object()
        if self.object.state != 1:
            return False
        return True

    def get_form_class(self):
        self.object = self.get_object()
        if self.object.assigned.state == 1:
            return UpdateHitFormActiveHitman
        else:
            return UpdateHitFormInactiveHitman

apps/hits/templates/hits/hit_bulk.html
{% extends "base/list.html" %}
{% load crispy_forms_tags hits %}
{% block navigation_extra %}
  {% include "base/nav_without_url.html" with label='Hits' %}
{% endblock %}
{% block content_title %}
  Hits list to bulk reassignment!
{% endblock %}
{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {% if form.errors %}
      <span style="color: red;">
      {{ form.errors }}
      </span>
    {% endif %}
    {{ form.hitman|as_crispy_field }}
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th scope="col">Key</th>
          <th scope="col">Target</th>
          <th scope="col">Mission Description</th>
          <th scope="col">Assigned</th>
          <th scope="col">Creator</th>
          <th scope="col">State</th>
          <th scope="col">Select</th>
        </tr>
        </thead>
        <tbody>
        {% for choice in form.hits %}
          <tr>
            <th scope="row">{{ choice.data.value.instance.pk }}</th>
            <td>{{ choice.data.value.instance.target_name }}</td>
            <td>{{ choice.data.value.instance.mission_description }}</td>
            <td>{{ choice.data.value.instance.assigned }}</td>
            <td>{{ choice.data.value.instance.creator }}</td>
            <td>{{ choice.data.value.instance.get_state_display }}</td>
            <td>
              <input class="form-check-input" type="checkbox" id="{{ choice.data.attrs.id }}" name="hits"
                     value="{{ choice.data.value.instance.pk }}">
            </td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </div>
    <hr>
    <button type="submit" class="btn btn-success">Bulk reassignment!</button>
  </form>

{% endblock %}

apps/hits/templates/hits/hit_detail.html
{% extends "base/base_detail.html" %}

{% block content_title %}
  {% if object.state == 1 %}
    {% if request.user.pk == 1 or object.assigned.boss.pk == request.user.pk %}
      <a href="edit/"><i class="fas fa-edit"></i></a>
    {% endif %}
  {% endif %} Hit detail: {{ object.pk }} ({{ object.get_state_display }})
{% endblock %}

{% block navigation_extra %}
  {% include "base/nav_with_url.html" with url=object.get_list_url label='Hits' %}
  {% include "base/nav_without_url.html" with label=object %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <h5 class="text-primary">Assigned</h5>
      <p>{{ object.assigned }}</p>
    </div>
    <div class="col-12">
      <h5 class="text-primary">Description</h5>
      <p>{{ object.mission_description|default:"Without description" }}</p>
    </div>
    <div class="col-12">
      <h5 class="text-primary">Target</h5>
      <p>{{ object.target_name|default:"Without description" }}</p>
    </div>
    <div class="col-12">
      <h5 class="text-primary">Created by</h5>
      <p>{{ object.creator.get_full_name }}</p>
    </div>
  </div>
{% endblock %}

apps/hits/templates/hits/hit_form.html
{% extends "base/list.html" %}
{% load crispy_forms_tags %}
{% block navigation_extra %}
  {% url 'hits:list' as hits_list %}
  {% include "base/nav_with_url.html" with url=hits_list label='Hits' %}
  {% include "base/nav_without_url.html" with label='Create hit' %}
{% endblock %}
{% block content_title %}
  Hits create!
{% endblock %}
{% block content %}
  <div class="row justify-content-md-center">
    <div class="col-11">
      <form method="post" class="create-form" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        {% block submit %}
          <button type="submit" class="btn btn-success">Create</button>
        {% endblock %}
      </form>
    </div>
  </div>
{% endblock %}

apps/hits/templates/hits/hit_list.html
{% extends "base/list.html" %}
{% block navigation_extra %}
  {% include "base/nav_without_url.html" with label='Hits' %}
{% endblock %}
{% block content_title %}
  Hits list! {% if request.user.pk == 1 or request.user.subordinates.all %}
  <a href="{% url 'hits:create' %}"><i class="fas fa-plus"></i></a>
{% endif %}
{% endblock %}
{% block content %}
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Assigned</th>
        <th scope="col">Creator</th>
        <th scope="col">Target</th>
        <th scope="col">State</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for object in object_list %}
        <tr>
          <th scope="row">{{ object.pk }}</th>
          <td>{{ object.assigned }}</td>
          <td>{{ object.creator }}</td>
          <td>{{ object.target_name }}</td>
          <td>{{ object.get_state_display }}</td>
          <td>
            <a href="{% url 'hits:detail' object.pk %}" title="Detail"><i class="fas fa-eye"></i></a>
          </td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  </div>
  <hr>
  <a href="{% url 'hits:bulk' %}" class="btn btn-success">Bulk reassignment!</a>
{% endblock %}

apps/hits/templates/hits/hit_update.html
{% extends 'hits/hit_form.html' %}
{% block content_title %}
  Updating Hit #: {{ object.pk }}
{% endblock %}
{% block navigation_extra %}
  {% url 'hits:list' as hits_list %}
  {% include "base/nav_with_url.html" with url=hits_list label='Hits' %}
  {% include "base/nav_with_url.html" with url=object.get_detail_url label=object %}
  {% include "base/nav_without_url.html" with label='Update hit' %}
{% endblock %}
{% block submit %}
  <button type="submit" class="btn btn-success">Update!</button>
{% endblock %}