apps/authentication/urls.py
"""Auth models."""

# Django
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

# Views
from apps.authentication.views import (
    HitmanListView,
    HitmanDetailView,
    CreateBossView,
    RegisterView,
)

app_name = "auth"

urlpatterns = (
    # path(
    #    route="register/",
    #    view=RegisterView.as_view(),
    #    name="register",
    # ),
    path(
        route="",
        view=LoginView.as_view(
            template_name="authentication/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path(
        route="register/",
        view=RegisterView.as_view(),
        name="register",
    ),
    path(
        route="logout/",
        view=LogoutView.as_view(),
        name="logout",
    ),
    path(
        route="hitmen/",
        view=login_required(HitmanListView.as_view()),
        name="hitmen_list",
    ),
    path(
        route="hitmen/<int:pk>/",
        view=login_required(HitmanDetailView.as_view()),
        name="hitmen_detail",
    ),
    path(
        route="hitmen/manager/",
        view=login_required(CreateBossView.as_view()),
        name="hitmen_assign_manager",
    ),
)

apps/hits/urls.py
"""Auth models."""

# Django
from django.urls import path

# Local
from apps.hits.views import (
    HitListView,
    HitDetailView,
    HitCreateView,
    HitUpdateView,
    HitBulkUpdate,
)

app_name = "hits"

urlpatterns = (
    path(
        route="hits/",
        view=HitListView.as_view(),
        name="list",
    ),
    path(
        route="hits/bulk/",
        view=HitBulkUpdate.as_view(),
        name="bulk",
    ),
    path(
        route="hits/create/",
        view=HitCreateView.as_view(),
        name="create",
    ),
    path(
        route="hits/<int:pk>/",
        view=HitDetailView.as_view(),
        name="detail",
    ),
    path(
        route="hits/<int:pk>/edit/",
        view=HitUpdateView.as_view(),
        name="update",
    ),
)

apps/transitions/urls.py
"""Auth models."""

# Django

from django.urls import path

# Local
from apps.transitions.views import TransitionView

app_name = "transitions"

urlpatterns = (
    path(
        route="transition/<slug:transition>/<slug:app>/<slug:model>/<int:pk>/",
        view=TransitionView.as_view(),
        name="transition",
    ),
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

# View
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("", include("apps.hits.urls")),
    path("", include("apps.transitions.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}Hits application {% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

  {% include 'base/sidebar.html' %}

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small"
                         placeholder="Search for..." aria-label="Search"
                         aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>
          <!-- Nav Item - Alerts -->

          <!-- Nav Item - Messages -->

          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.get_full_name }}</span>
                <img class="img-profile rounded-circle"
                     src="{% static 'img/undraw_profile.svg' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                   aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          {% endif %}
        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            {% block navigation_extra %}

            {% endblock %}
          </ol>
        </nav>
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">{% block content_title %}
          Welcome to Hits application!
        {% endblock %}
        </h1>
        {% block transitions %}
        {% endblock %}
        {% block content %}
          <div class="row">
            <div class="col-12">
              <p>This is a dummy spy and hits management app </p>
            </div>
          </div>
        {% endblock %}

      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Develop by <a href="https://github.com/jhurtadojerves" target="_blank">Juliens</a></span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
{% if request.user.is_authenticated %}

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url  'auth:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>
{% endif %}

{% for message in messages %}
  <i class="d-none toast-message" data-tags="{{ message.tags }}"
     data-message="{{ message }}"></i>
{% endfor %}
{% block js %}
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static  'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'js/transition.js' %}"></script>
  <script>
    const toastMixin = Swal.mixin({
      toast: true,
      icon: 'success',
      title: 'General Title',
      animation: true,
      position: 'top-right',
      showConfirmButton: false,
      timer: 3000,
      timerProgressBar: true,
      didOpen: (toast) => {
        toast.addEventListener('mouseenter', Swal.stopTimer)
        toast.addEventListener('mouseleave', Swal.resumeTimer)
      }
    });
    const toast_elements = [...document.getElementsByClassName("toast-message")]
    toast_elements.map(element => {
      console.log(element.dataset.tags)
      new toastMixin({
        icon: element.dataset.tags,
        title: element.dataset.message,
        padding: '2em',
      })
    })
  </script>
{% endblock %}
</body>

</html>

templates/base/base_detail.html
{% extends 'base/base.html' %}
{% load transitions %}
{% block transitions %}
  {% if object.get_available_state_transitions %}
    <div class="row">
      <div class="col-12">{% get_meta_data object as data %}
        {% for transition in object.get_available_state_transitions %}
          <a href="#"
             class="btn btn-{{ transition.custom.btn }} transition"
             data-url="{% url 'transitions:transition' transition.name data.app_name data.model_name object.pk %}">
            {{ transition.custom.verbose }}
          </a>
        {% endfor %}</div>
    </div>
    <hr>
  {% endif %}
{% endblock %}

templates/base/detail.html
{% extends "base/base.html" %}

templates/base/list.html
{% extends "base/base.html" %}

{% block content %}
{% endblock %}

templates/base/nav_with_url.html
<li class="breadcrumb-item"><a href="{{ url }}">{{ label }}</a></li>

templates/base/nav_without_url.html
<li class="breadcrumb-item active">{{ label }}</li>

templates/base/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-skull-crossbones"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Hits</div>
  </a>


  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Hits
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'auth:hitmen_list' %}">
      <i class="fas fa-fw fa-user-alt"></i>
      <span>Hitmen</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{%  url 'hits:list' %}">
      <i class="fas fa-fw fa-book-dead"></i>
      <span>Hits</span></a>
  </li>

</ul>
<!-- End of Sidebar -->